/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const EnquiryId = IDL.Nat;
export const Enquiry = IDL.Record({
  'id' : EnquiryId,
  'status' : IDL.Text,
  'serviceType' : IDL.Text,
  'duration' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
  'budgetRange' : IDL.Text,
  'location' : IDL.Text,
  'eventDate' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const EnquiryInput = IDL.Record({
  'serviceType' : IDL.Text,
  'duration' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
  'budgetRange' : IDL.Text,
  'location' : IDL.Text,
  'eventDate' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteEnquiry' : IDL.Func([EnquiryId], [], []),
  'getAllEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
  'getAndMarkEnquiryAsContacted' : IDL.Func([EnquiryId], [Enquiry], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEnquiriesByStatus' : IDL.Func([IDL.Text], [IDL.Vec(Enquiry)], ['query']),
  'getEnquiry' : IDL.Func([EnquiryId], [Enquiry], ['query']),
  'getEnquiryCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasEnquiries' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitEnquiry' : IDL.Func([EnquiryInput], [EnquiryId], []),
  'updateEnquiryStatus' : IDL.Func([EnquiryId, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const EnquiryId = IDL.Nat;
  const Enquiry = IDL.Record({
    'id' : EnquiryId,
    'status' : IDL.Text,
    'serviceType' : IDL.Text,
    'duration' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
    'budgetRange' : IDL.Text,
    'location' : IDL.Text,
    'eventDate' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const EnquiryInput = IDL.Record({
    'serviceType' : IDL.Text,
    'duration' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
    'budgetRange' : IDL.Text,
    'location' : IDL.Text,
    'eventDate' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteEnquiry' : IDL.Func([EnquiryId], [], []),
    'getAllEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
    'getAndMarkEnquiryAsContacted' : IDL.Func([EnquiryId], [Enquiry], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEnquiriesByStatus' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Enquiry)],
        ['query'],
      ),
    'getEnquiry' : IDL.Func([EnquiryId], [Enquiry], ['query']),
    'getEnquiryCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasEnquiries' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitEnquiry' : IDL.Func([EnquiryInput], [EnquiryId], []),
    'updateEnquiryStatus' : IDL.Func([EnquiryId, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };